site:
  name: "Earthject"
  title: "Earthject — Sustainable Solutions for a Better World"
  description: "Crowdfunding climate action through community impact"
  url: "https://earthject.com"  # Replace with your custom domain when ready
  author: "Earthject Team"
  language: "en-US"

social:
  twitter: "https://x.com/earthject?s=21&t=43GaHG5AuaSXcDsOKAFLTQ"
  github: "https://github.com/JSjames86/earthject-site"
  linkedin: "https://www.linkedin.com/company/earthject"
  instagram: "https://www.instagram.com/earthject"
  facebook: "https://www.facebook.com/earthject"
  tiktok: "https://www.tiktok.com/@earthject"
  discord: "https://discord.gg/7c45mK2pTN"
  reddit: "https://www.reddit.com/r/Earthject"
  patreon: "https://www.patreon.com/user?u=183338080&utm_campaign=creatorshare_creator"

openGraph:
  type: "website"
  title: "Earthject — Sustainable Solutions for a Better World"
  description: "Crowdfunding climate action through community impact"
  image: "/assets/images/og-image.png"  # Replace with your own Open Graph image