site:
  name: "Earthject"
  title: "Earthject — Sustainable Solutions for a Better World"
  description: "Crowdfunding climate action through community impact"
  url: "https://earthject.com"  # Replace with your custom domain when ready
  author: "Earthject Team"
  language: "en-US"

social:
  twitter: "https://x.com/earthject?s=21&t=43GaHG5AuaSXcDsOKAFLTQ"
  github: "https://github.com/JSjames86/earthject-site"
  linkedin: "https://www.linkedin.com/company/earthject"
  instagram: "https://www.instagram.com/earthject"
  facebook: "https://www.facebook.com/earthject"
  tiktok: "https://www.tiktok.com/@earthject"
  discord: "https://discord.gg/7c45mK2pTN"
  reddit: "https://www.reddit.com/r/Earthject"
  patreon: "https://www.patreon.com/user?u=183338080&utm_campaign=creatorshare_creator"

openGraph:
  type: "website"
  title: "Earthject — Sustainable Solutions for a Better World"
  description: "Crowdfunding climate action through community impact"
  image: "/assets/images/og-image.png"  # Replace with your own Open Graph image

metadata:
  title:
    default: "Earthject"
    template: "%s — Earthject"
  description: "Crowdfunding climate action through community impact."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: "Earthject"
    images:
      - url: "/assets/images/og-image.png"
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@earthject'
    site: '@earthject'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"